### ISSUE TITLE
sizeX decamelized as sizex

### ISSUE THREAD

**Issue by ZdenekM** [nficano/humps#127]
**Describe the bug**
String 'sizeX' is correctly identified as camelCase but is converted to snake_case as 'sizex'.

**To Reproduce**
```python
>>> humps.is_camelcase("sizeX")
True
>>> humps.decamelize("sizeX")
'sizex'
>>> humps.decamelize("camelCaseTest")
'camel_case_test'
```

**Expected behavior**
```python
>>> humps.decamelize("sizeX")
'size_x'
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04, Python 3.8
 - Version 1.6.1

**Comment by noamgat** [comment]
Was about to open the exact same issue. +1

**Comment by ZdenekM** [comment]
@nficano Great, many thanks! ;-)
