### ISSUE TITLE
camelize on ALL CAPS doesn't change the string to camel case

### ISSUE THREAD

**Issue by nitinkatkam** [nficano/humps#156]
**Describe the bug**
Pass an all-caps string to camelize. The output is still an all-caps string.

**To Reproduce**
print(humps.camelize('NITIN REDDY'))

**Expected behavior**
Output: "nitinReddy"

**Actual behavior**
Output: "NITIN REDDY"

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.1
 - Version: Python 3.7.3

**Comment by ronnie-llamado** [comment]
There's currently a check in `camelize` to see if the string passed in is all uppercase (see lines 77-78). If it is, then it will return the same string back without modification. 

https://github.com/nficano/humps/blob/0b9a4ef1ca7df3f57e309ca8570282332ff0e2f1/humps/main.py#L59-L78


A workaround for this would be to convert the string to lowercase before passing it into `camelize`:
```python
>>> humps.camelize("NITIN REDDY".lower())
'nitinReddy'
```
