### ISSUE TITLE
"_id" gets converted to "_d"

### ISSUE THREAD

**Issue by smn-snkl** [nficano/humps#2]
**Describe the bug**
When using camelize on "_id" it gets converted to "_d"

**To Reproduce**
1. Create dict with "_id" key, e.g. tmp = {"_id": "123"}
2. Convert using humps.camelize(tmp)

**Expected behavior**
Not sure. Either _Id, _id or id ...

**Comment by smn-snkl** [comment]
Btw, thanks for creating this @nficano.

**Comment by nficano** [comment]
very interesting! looking into it

**Comment by Ak4zh** [comment]
Another issue is {"itemID": "xxxx"} converts to {"itemid": "xxxx"}

**Comment by ronnie-llamado** [comment]
Closed by #167
