### ISSUE TITLE
[question] Abbreviation conversion assymetry workarounds

### ISSUE THREAD

**Issue by aphilas** [nficano/humps#269]
I am using pyhumps and pydantic to serialize/deserialize data from an API. I have certain properties with abbreviations such as `URL`. `decamelize`-ing the data works fine. However, after I'm done "processing" it, how can I retain the capitalization of said abbreviations with `camelize`. 

Example:
```py
# input propery "CallBackURL"

humps.decamelize("CallBackURL") # "call_back_url"
humps.camelize("call_back_url") # "CallBackUrl"
```

I could traverse the data and replace the specific properties, which I am doing currently, but I am wondering if there is a more elegant way to do it. 

<details>
<summary>Initial thoughts</summary>

My first thought was maybe humps could be made "abbreviation-aware" through extra parameters. 
```py
humps.camelize([{"call_back_url": ""}], uppercase_abbreviations=True) # use a store of "common" abbreviations
# OR
humps.camelize([{"call_back_url": ""}], abbreviations=("url")) # pass in abbreviations
```
Might this be beyond the scope of humps? Or is it too inflexible?

</details>

**Comment by aphilas** [comment]
Just figured I could use [pydantic aliases](https://pydantic-docs.helpmanual.io/usage/schema/#field-customization) for now, for each field with that specific usecase. Or configure a custom [alias generator](https://pydantic-docs.helpmanual.io/usage/model_config/#alias-generator).

**Comment by ificiana** [comment]
@aphilas while such a feature would be really helpful, implementing it without ambiguity is hard, if not nearly impossible.
Let's say we have "CurlURL", how would the program know if it is CURLurl or CurlURL or CURLURL. 
As for a list of common abbreviations, that would make stuff far from being lightweight and the ambiguity issue still remains...

**Comment by aphilas** [comment]
You're right. The ambiguity is inevitable. 

Thanks.
