### ISSUE TITLE
camelizeKeys only rather than the full dictionary (values and keys)

### ISSUE THREAD

**Issue by robinwkurtz** [nficano/humps#294]
**Is your feature request related to a problem? Please describe.**
It would be nice to have the ability to only camelize a dictionary's keys, rather than all of the values as wwell.

**Describe the solution you'd like**
https://github.com/domchristie/humps#humpscamelizekeysobject-options -- Converts object keys to camelCase. It also converts arrays of objects.

**Describe alternatives you've considered**
Looping over the dictionary myself and using `humps.camelize` on keys only

**Additional context**
Thanks for the great tool!

**Comment by ificiana** [comment]
@robinwkurtz Hi, thanks for opening the issue. Sorry, but I couldn't replicate the problem. It'd be nice if you could list some use cases. I did this:
```py
>>> d = {"s_gv": "j_db", "ir_o": "op_m"}
>>> humps.camelize(d)
{'sGv': 'j_db', 'irO': 'op_m'}
```
`camelize` does appear to be converting only the keys

However, it's worth noting that if the values include a mapping, it will convert their keys as well:
```py
>>> d = {"s_gv": "j_db", "sub_dict": {"ir_o": "op_m"}}
>>> humps.camelize(d)
{'sGv': 'j_db', 'subDict': {'irO': 'op_m'}}
```

Currently, there's no way to limit this behaviour but there's an old issue requesting a similar functionality here: #233

**Comment by robinwkurtz** [comment]
Thanks for the comment @ificiana, my issue was in fact json.dumps which I was using within the camilize function.

```python
>>> d = {"s_gv": "j_db", "ir_o": "op_m"}

>>> print('plain', d)
plain {'s_gv': 'j_db', 'ir_o': 'op_m'}

>>> print('humps', humps.camelize(d))
humps {'sGv': 'j_db', 'irO': 'op_m'}

>>> print('json', json.dumps(d))
json {"s_gv": "j_db", "ir_o": "op_m"}

>>> print('humps.json', humps.camelize(json.dumps(d)))
humps.json {"sGv":"jDb","irO":"opM"}

>>> print('json.humps', json.dumps(humps.camelize(d)))
json.humps {"sGv": "j_db", "irO": "op_m"}
```

I'm trying to camlize the keys of a large dataclass before sending it through a request, and I guess the combination of the two do not work well together.

Sorry for the issue!

**Comment by ificiana** [comment]
Right! I see, no problem. `json.dumps` returns a string which `camelize` processes as a string in place of a mapping. So, your "json.humps" is the way to go. `camelize` the mapping first, then `json.dumps` the output. Anyway, have a nice day!
