### ISSUE TITLE
Changing parsing of acronyms at end of sentence

### ISSUE THREAD

**Issue by samlobel** [nficano/humps#3]
I understand there's a lot of ambiguity in converting certain keys. The decamelization of `APIResponse` to `api_response` seems perfectly correct. But, this behavior gives odd results when the acronym extends to the end of the word. For example,

```
import humps
humps.decamelize('responseAPI') # 'response_ap_i'
humps.decamelize('API') # 'ap_i'
```

It seems that it thinks the final capitalized letter is part of the next word. I would propose changing the parsing behavior to only split the capitals from an acronym if it is followed by a lowercase.

Thanks! If I get around to it I'll try and make a PR. Let me know if that's something you'd like.

**Comment by ronnie-llamado** [comment]
No issue seen in v3.0.2

/close
