### ISSUE TITLE
Issue with single letter word between two

### ISSUE THREAD

**Issue by grolig** [nficano/humps#61]
**Describe the bug**
Hi, then words are followed by single character word next underscore is not converted.

**To Reproduce**
humps.camelize('test_n_test')
result: testN_test

**Expected behavior**
result : testNTest

**Comment by kevlarr** [comment]
Just noticed this too - I was expecting a field like `p_value` to get camel-cased to `pValue`

**Comment by dereklukacs** [comment]
bump on this issue.

similar to @kevlarr , decamelize properly does

 `pValue` ---decamel--> `p_value`

`p_value` ---camel---> `p_value`

I would expect this to be symmetric.
