### ISSUE TITLE
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

### ISSUE THREAD

**Issue by bakert** [nficano/humps#92]
**Describe the bug**
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working

**To Reproduce**
```
[prak humps] python3 --version
Python 3.8.2
[prak humps] python3 main.py
main.py:7: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
  from collections import Mapping
```

**Expected behavior**
No DeprecationWarning

**Desktop (please complete the following information):**
 - OS: OS X
- Python: 3.8.2

**Comment by bakert** [comment]
I submitted PR #93 to fix this.

**Comment by nphilou** [comment]
Hi, thanks for contributing, it was a duplicate with #79 which I just merged.
